config/routes.rb
Rails.application.routes.draw do
  resources :triangles

end

app/models/triangle.rb
class Triangle < ActiveRecord::Base
  validates :adjacent_leg, :opposite_leg, :hypotenuse, presence: true
  validates :adjacent_leg, :opposite_leg, :hypotenuse, numericality: { greater_than_or_equal_to: 0.0 }

  validates_with ProperTriangleValidator
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/triangles_controller.rb
class TrianglesController < ApplicationController
  before_action :set_triangle, only: [:show, :edit, :update, :destroy]

  # GET /triangles
  # GET /triangles.json
  def index
    @triangles = Triangle.all
  end

  # GET /triangles/1
  # GET /triangles/1.json
  def show
  end

  # GET /triangles/new
  def new
    @triangle = Triangle.new
  end

  # GET /triangles/1/edit
  def edit
  end

  # POST /triangles
  # POST /triangles.json
  def create
    @triangle = Triangle.new(triangle_params)

    respond_to do |format|
      if @triangle.save
        format.html { redirect_to @triangle, notice: 'Triangle was successfully created.' }
        format.json { render :show, status: :created, location: @triangle }
      else
        format.html { render :new }
        format.json { render json: @triangle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /triangles/1
  # PATCH/PUT /triangles/1.json
  def update
    respond_to do |format|
      if @triangle.update(triangle_params)
        format.html { redirect_to @triangle, notice: 'Triangle was successfully updated.' }
        format.json { render :show, status: :ok, location: @triangle }
      else
        format.html { render :edit }
        format.json { render json: @triangle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /triangles/1
  # DELETE /triangles/1.json
  def destroy
    @triangle.destroy
    respond_to do |format|
      format.html { redirect_to triangles_url, notice: 'Triangle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_triangle
      @triangle = Triangle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def triangle_params
      params.require(:triangle).permit(:adjacent_leg, :opposite_leg, :hypotenuse)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/triangles_helper.rb
module TrianglesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AppWithValidations</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/triangles/_form.html.erb
<%= form_for(@triangle) do |f| %>
  <% if @triangle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@triangle.errors.count, "error") %> prohibited this triangle from being saved:</h2>

      <ul>
      <% @triangle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :adjacent_leg %><br>
    <%= f.text_field :adjacent_leg %>
  </div>
  <div class="field">
    <%= f.label :opposite_leg %><br>
    <%= f.text_field :opposite_leg %>
  </div>
  <div class="field">
    <%= f.label :hypotenuse %><br>
    <%= f.text_field :hypotenuse %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/triangles/edit.html.erb
<h1>Editing triangle</h1>

<%= render 'form' %>

<%= link_to 'Show', @triangle %> |
<%= link_to 'Back', triangles_path %>

app/views/triangles/index.html.erb
<h1>Listing triangles</h1>

<table>
  <thead>
    <tr>
      <th>Adjacent leg</th>
      <th>Opposite leg</th>
      <th>Hypotenuse</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @triangles.each do |triangle| %>
      <tr>
        <td><%= triangle.adjacent_leg %></td>
        <td><%= triangle.opposite_leg %></td>
        <td><%= triangle.hypotenuse %></td>
        <td><%= link_to 'Show', triangle %></td>
        <td><%= link_to 'Edit', edit_triangle_path(triangle) %></td>
        <td><%= link_to 'Destroy', triangle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Triangle', new_triangle_path %>

app/views/triangles/new.html.erb
<h1>New triangle</h1>

<%= render 'form' %>

<%= link_to 'Back', triangles_path %>

app/views/triangles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Adjacent leg:</strong>
  <%= @triangle.adjacent_leg %>
</p>

<p>
  <strong>Opposite leg:</strong>
  <%= @triangle.opposite_leg %>
</p>

<p>
  <strong>Hypotenuse:</strong>
  <%= @triangle.hypotenuse %>
</p>

<%= link_to 'Edit', edit_triangle_path(@triangle) %> |
<%= link_to 'Back', triangles_path %>